image: docker:latest
services:
  - docker:dind

stages:
  #   - test
  - build

# test:
#   image: golang:1.14.3-stretch
#   stage: test
#   script:
#     - go mod download
#     - go test -v --cover ./...
#     - go build ./...
#   only:
#     - master
#     - merge_requests

build:
  stage: build
  before_script:
    - docker info
    - echo ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
  script:
    - echo "build"
    - docker build -f Dockerfile -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA} .
    - docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA} ${CI_REGISTRY_IMAGE}:latest
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
    - docker push ${CI_REGISTRY_IMAGE}:latest
  only:
    - master
    - merge_requests
