// Code generated by entc, DO NOT EDIT.

package areahistory

const (
	// Label holds the string label denoting the areahistory type in the database.
	Label = "areahistory"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldWalletID holds the string denoting the walletid field in the database.
	FieldWalletID = "WalletID"
	// FieldProvinceNameTH holds the string denoting the provincenameth field in the database.
	FieldProvinceNameTH = "ProvinceNameTH"
	// FieldDistrictNameTH holds the string denoting the districtnameth field in the database.
	FieldDistrictNameTH = "DistrictNameTH"
	// FieldSubDistrict holds the string denoting the subdistrict field in the database.
	FieldSubDistrict = "SubDistrict"
	// FieldRankArea holds the string denoting the rankarea field in the database.
	FieldRankArea = "RankArea"
	// FieldDateCalRank holds the string denoting the datecalrank field in the database.
	FieldDateCalRank = "DateCalRank"

	// Table holds the table name of the areahistory in the database.
	Table = "area_history"
)

// Columns holds all SQL columns for areahistory fields.
var Columns = []string{
	FieldID,
	FieldWalletID,
	FieldProvinceNameTH,
	FieldDistrictNameTH,
	FieldSubDistrict,
	FieldRankArea,
	FieldDateCalRank,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// WalletIDValidator is a validator for the "WalletID" field. It is called by the builders before save.
	WalletIDValidator func(string) error
	// ProvinceNameTHValidator is a validator for the "ProvinceNameTH" field. It is called by the builders before save.
	ProvinceNameTHValidator func(string) error
	// DistrictNameTHValidator is a validator for the "DistrictNameTH" field. It is called by the builders before save.
	DistrictNameTHValidator func(string) error
	// SubDistrictValidator is a validator for the "SubDistrict" field. It is called by the builders before save.
	SubDistrictValidator func(string) error
)
